- id: pyall
  name: pyall
  description:
    "Pyall is a linter that tries to keep the __all __ in your Python modules always up
    to date."
  entry: pyall
  language: python
  language_version: python3
  types: [python]
